### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Shafi2016** [pat-alt/deepvars#1]
Hello @pat-alt  I am trying to install but getting the following error: 
```
devtools::install_github("pat-alt/deepvars", build_vignettes=TRUE)
Error: Failed to install 'unknown package' from GitHub:
  Line starting '<<<<<<< HEAD ...' is malformed!
```

**Comment by pat-alt** [comment]
Hi @Shafi2016 , thanks very much for flagging. This was an artefact of a previous merge conflict and has been fixed now. Hopefully the installation should work now (checks have passed). Thanks again!

**Comment by Shafi2016** [comment]
Thank you @pat-alt, I am still getting some other errors. Do I need TensorFlow for it?

E  creating vignettes (24.1s)
   --- re-building 'SVARs.Rmd' using rmarkdown
   Warning in prepare_var_data(data, lags = lags, constant = constant, standardize = standardize) :
     Date indexing is only implemented for date of class Date. Using simple integer index instead.
   --- finished re-building 'SVARs.Rmd'
   
   --- re-building 'VARs.Rmd' using rmarkdown
   Don't know how to automatically pick scale for object of type yearqtr. Defaulting to continuous.
   Warning in prepare_var_data(data, lags = lags, constant = constant, standardize = standardize) :
     Date indexing is only implemented for date of class Date. Using simple integer index instead.
   Warning in prepare_var_data(data, lags = lags, constant = constant, standardize = standardize) :
     Date indexing is only implemented for date of class Date. Using simple integer index instead.
   Warning in melt.data.table(data.table::as.data.table(solve(crossprod(X),  :
     id.vars and measure.vars are internally guessed when both are 'NULL'. All non-numeric/integer/logical type columns are considered id.vars, which in this case are columns []. Consider providing at least one of 'id' or 'measure' vars in future.
   Don't know how to automatically pick scale for object of type yearqtr. Defaulting to continuous.
   Warning in prepare_var_data(data, lags = lags, constant = constant, standardize = standardize) :
     Date indexing is only implemented for date of class Date. Using simple integer index instead.
   The VAR is stable.
   --- finished re-building 'VARs.Rmd'
   
   --- re-building 'deepvars.Rmd' using rmarkdown
   Warning in prepare_var_data(data, lags = lags, constant = constant, standardize = standardize) :
     Date indexing is only implemented for date of class Date. Using simple integer index instead.
   Warning in prepare_var_data(data, lags = lags, standardize = TRUE) :
     Date indexing is only implemented for date of class Date. Using simple integer index instead.
   Quitting from lines 78-82 (deepvars.Rmd) 
   Error: processing vignette 'deepvars.Rmd' failed with diagnostics:
   Valid installation of TensorFlow not found.
   
   Python environments searched for 'tensorflow' package:
    C:\Users\shafi\AppData\Local\r-miniconda\envs\r-reticulate\python.exe
   
   Python exception encountered:
    ModuleNotFoundError: No module named 'tensorflow'
   
   Detailed traceback:
     File "C:\Users\shafi\Documents\R\win-library\4.1\reticulate\python\rpytools\loader.py", line 44, in _import_hook
       level=level

**Comment by Shafi2016** [comment]
Thank you @pat-alt. Do you have any basic examples for the DeepVAR model?

**Comment by pat-alt** [comment]
Your point on TensorFlow was also useful @Shafi2016, I've just updated the README and tried to automate the configuration for future users. 

As for basic examples, I need to add the full documentation. In the meantime the package vignettes should be helpful. Have you tried running `utils::browseVignettes('deepvars')` after installing the package?
